### ISSUE TITLE
Command brew which-update fails

### ISSUE THREAD

**Issue by olfway** [Homebrew/homebrew-command-not-found#137]
I'm just added command-not-found tap and cannot run which-update:

```
% brew which-update
==> Using executables list from '/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/executables.txt'
Error: missing keywords: flags, ignore_errors
Warning: Removed Sorbet lines from backtrace!
/opt/homebrew/Library/Homebrew/formulary.rb:132:in `load_formula_from_path'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:64:in `block (2 levels) in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `block in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/which_update.rb:51:in `update_and_save!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/which-update.rb:41:in `which_update'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

Homebrew version:
```
% brew --version
Homebrew 4.1.17-33-g13ca5c3
Homebrew/homebrew-core (git revision ca924ee3875; last commit 2023-10-28)
Homebrew/homebrew-cask (git revision c9f9182d01; last commit 2023-10-27)
```

Command which-formula is working:
```
% brew which-formula identify
imagemagick
imagemagick@6
```

**Comment by woodruffw** [comment]
Thanks for the report; looks like a regression on my part. Triaging now.

**Comment by woodruffw** [comment]
@olfway I've opened #138 with a prospective fix here. Could you give those changes a try and see if they resolve the failure for you?
