### ISSUE TITLE
Error: undefined method `install_tap' for Homebrew:Module

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-command-not-found#31]
With Linuxbrew:

```
$ brew which-update --stats executables.txt 
Error: undefined method `install_tap' for Homebrew:Module
/home/baptiste/.linuxbrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:160:in `block in <top (required)>'
/home/baptiste/.linuxbrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:158:in `each'
/home/baptiste/.linuxbrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:158:in `flat_map'
/home/baptiste/.linuxbrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:158:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/baptiste/.linuxbrew/Library/brew.rb:21:in `require?'
/home/baptiste/.linuxbrew/Library/brew.rb:89:in `<main>'

$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 44cbc9f7147442c2aa029795780833fa72ce69c9
Last commit: il y a 2 jours
HOMEBREW_PREFIX: /home/baptiste/.linuxbrew
HOMEBREW_REPOSITORY: /home/baptiste/.linuxbrew
HOMEBREW_CELLAR: /home/baptiste/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit broadwell
Kernel: Linux 4.2.0-35-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.4 LTS
Codename: trusty
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.7.0_95
```

**Comment by xu-cheng** [comment]
Try to use `Tap#install`. `install_tap` has been deprecated for long time.

**Comment by ilovezfs** [comment]
require "cmd/tap" works if you need a quick fix

**Comment by bfontaine** [comment]
Yeah I’m at work I documented the issue to fix it tonight :smiley:
