### ISSUE TITLE
Error with brew which-update: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by yetisyny** [Homebrew/homebrew-command-not-found#47]
When I run `brew which-update`, I now get the following error:

```
==> Using executables list from '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/executables.txt'
Error: undefined method `split' for nil:NilClass
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:34:in `block in initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:32:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:32:in `initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:198:in `new'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-update.rb:198:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
```

The command `brew which-update` does not work anymore, it just generates that error message. `brew command-not-found-init` and `brew which-formula` still work, thankfully. This is a new problem and did not happen before, `brew which-update` worked until recently. I got this problem after running `brew update` as usual today. I am on macOS 10.12 Sierra and the rest of homebrew works fine right now, no problems at all with` brew doctor`.

**Comment by bfontaine** [comment]
I can’t reproduce locally, but 7c30c8107d59c975a8c7a9a6ae54d5caf0c65077 should fix the issue.

**Comment by yetisyny** [comment]
You fixed it, you can mark it as resolved, I don’t get that error anymore, thanks.
