### ISSUE TITLE
`brew which-formula` doesn't work

### ISSUE THREAD

**Issue by schrodincat** [Homebrew/homebrew-command-not-found#57]
For some reason `brew which-formula` doesn't work for me.

`brew which-formula when` returns:

```
Error: private method `flag?' called for ["when"]:Array
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-which-formula.rb:74:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

I'm using:
```
macOS Catalina 10.15.2 19C57
Homebrew 2.2.3-11-gdfe028a
```

**Comment by bfontaine** [comment]
This appears to be due to https://github.com/homebrew/brew/commit/d50a8c4e412293138877d6c1026e7bc83647d1d6

**Comment by bfontaine** [comment]
Fixed in https://github.com/Homebrew/homebrew-command-not-found/commit/0b5e783e4d8b79e6382c2b47cf0ef83a118a0fab; thanks for the heads-up! 🎉
